Tests livestatus: big simplification/factorization/clean.
test: fix: need --smallfiles for mongodb if low on disk space.

see https://test.savoirfairelinux.com/view/Shinken/job/Shinken-branch-1.4-Upstream-Commit-Short-Tests/18/testReport/junit/%3Cnose/suite/ContextSuite_context_TestConfigBig__setup/

lower system load impact on the assert.

Tests: Clean Livestatus tests.

step 1 : remove dead code.
step 2 : factorize in a common LiveStatus_Template class.. and use.

use_aggressive_host_checking seems rather required..

Fix: socket might already be completly closed by remote side.

Message d'erreur

[Errno 107] Transport endpoint is not connected
Pile d'exécution

Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/home/jenkins/workspace/Shinken-with-jenkins/test/test_livestatus_allowedhosts.py", line 131, in test_dont_allow_host
    self.assertFalse(self.query_livestatus("GET hosts\n\n"))
  File "/home/jenkins/workspace/Shinken-with-jenkins/test/test_livestatus_allowedhosts.py", line 90, in query_livestatus
    s.shutdown(socket.SHUT_WR)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 107] Transport endpoint is not connected

clean setup_with_file for undefined config_file check.

fix test_livestatus_mongo: use good cfg file.

Fix: testid must not be reset if it was already set

test: clean out last ref to nagios_xx method

clean bare assert_ in test_livestatus_mongodb.

fix/clean test mongo: don't import shinken.modules.logstore_mongodb if import pymongo failed.

+ skipIf instead of skipUnless (undefined in unittest2).